# This is a boilerplate parameters config generated for pipeline 'modelling'
# using Kedro 0.19.12.
#
# Documentation for this file format can be found in "Parameters"
# Link: https://docs.kedro.org/en/0.19.12/configuration/parameters.html
split:
  test_size: 0.2
  stratify: True
  random_state: 42

skip:
  skip_random_forest: False
  skip_logistic: False
  skip_lightgbm: False
  skip_xgboost: False

random_forest:
  n_estimators: 100
  max_depth: 10
  class_weight: balanced

logistic_regression:
  C: 1.0
  max_iter: 500
  solver: liblinear
  class_weight: balanced

lightgbm:
  n_estimators: 100
  learning_rate: 0.1
  max_depth: 6
  scale_pos_weight: 15  # matches
